spring.config.import=optional:application-secret.properties

spring.application.name=barbearia.agenda
server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=none

# Em PROD isso deve ser false; em DEV pode ser true (controlado por env var)
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}

spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:5}

mp.access-token=${MP_ACCESS_TOKEN:}
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:28800000}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

mp.notification-url=${MP_NOTIFICATION_URL:}
app.frontend-url=${APP_FRONTEND_UgRL:http://localhost:5173}

# WAHA
# ===============================
# WAHA - INTEGRAÇÃO WHATSAPP
# ===============================
waha.base-url=${WAHA_BASE_URL:http://devlikeapro/waha.railway.internal}
waha.api-key=${WAHA_API_KEY:wak_5GMY9103LCX+R91K}
waha.session=${WAHA_SESSION:default}
